### ISSUE TITLE
Broken view on firefox mobile on LG G6

### ISSUE THREAD

**Issue by the-coding-owl** [TYPO3-infrastructure/rm_typo3_forge_theme#5]
Hi, I have some view issues on firefox mobile. Something makes the view be scrollable horizontally and breaks the styling.
![Screenshot_20200106-212650](https://user-images.githubusercontent.com/6013986/71847573-7d7d1600-30cd-11ea-8e8a-9c9a3fa25822.png)
![Screenshot_20200106-213950](https://user-images.githubusercontent.com/6013986/71847581-84a42400-30cd-11ea-8d24-04dc7851a5cf.png)

**Comment by sgrossberndt** [comment]
https://gitlab.typo3.org/services/forge.typo3.org/typo3_forge_theme/-/issues/1
